Plugin movement to github
yoomoney/moira-trigger-plugin pull request #1
Opened 2021-09-06 07:42 UTC by karpenkovk

2021-09-06 07:51 UTC, f0y requested changes

2021-09-06 07:51 UTC, f0y commented on dependencies.gradle
> +    implementation "com.yandex.money.tech:moira-kotlin-client:1.0.3"
Здесь что-то пошло не так. Не должно быть яндекса. Внеси пжл изменения в moira-kotlin-client и moira-kotlin-dsl 
если требуется

2021-09-06 07:51 UTC, f0y commented on README.md
> +    moiraFromDirCompile 'com.yandex.money.tech:moira-kotlin-dsl:1.0.3'
Здесь аналогично. Никакого яндекса

2021-09-06 07:51 UTC, f0y commented on CHANGELOG.md
> +* `moira-trigger-plugin` перенесён в GitHub
Здесь побольше надо написать. Плюс версия не минорная.

2021-09-13 21:53 UTC, karpenkovk commented on dependencies.gradle
> +    implementation "com.yandex.money.tech:moira-kotlin-client:1.0.3"
Перенёс moira-kotlin-client и moira-kotlin-dsl:
https://github.com/yoomoney/moira-kotlin-dsl/pull/1
https://github.com/yoomoney/moira-kotlin-client/pull/1

2021-09-13 21:53 UTC, karpenkovk commented on README.md
> +    moiraFromDirCompile 'com.yandex.money.tech:moira-kotlin-dsl:1.0.3'
fixed

2021-09-13 21:53 UTC, karpenkovk commented on CHANGELOG.md
> +* `moira-trigger-plugin` перенесён в GitHub
Точно. Спасибо. Поправил.

2021-09-13 21:59 UTC, karpenkovk commented on src/test/kotlin/ru/yoomoney/gradle/plugins/moira/trigger/AbstractPluginSpec.kt
> +                maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
- [ ] Убрать после релиза moira-kotlin-dsl

2021-09-13 22:06 UTC, karpenkovk commented on src/test/kotlin/ru/yoomoney/gradle/plugins/moira/trigger/MoiraTriggerPluginSpec.kt
> +                moiraFromDirCompile 'ru.yoomoney.tech:moira-kotlin-dsl:1.4.1-feature-github-SNAPSHOT'
- [ ] `moiraFromDirCompile 'ru.yoomoney.tech:moira-kotlin-dsl:2.0.0`

2021-09-13 22:06 UTC, karpenkovk commented on src/test/kotlin/ru/yoomoney/gradle/plugins/moira/trigger/MoiraTriggerPluginSpec.kt
> +                moiraFromDirCompile 'ru.yoomoney.tech:moira-kotlin-dsl:1.4.1-feature-github-SNAPSHOT'
- [ ] `moiraFromDirCompile 'ru.yoomoney.tech:moira-kotlin-dsl:2.0.0`

2021-09-19 21:45 UTC, karpenkovk commented on dependencies.gradle
> +    implementation "com.yandex.money.tech:moira-kotlin-client:1.0.3"
обновлены moira-kotlin-dsl и moira-kotlin-client до версии 2.0.0

2021-09-24 13:05 UTC, layfe approved these changes

2021-09-29 10:50 UTC, f0y approved these changes

2021-09-29 17:10 UTC, merged